### ISSUE TITLE
Importing larger CZI files fail

### ISSUE THREAD

**Issue by SPPearce** [WolframResearch/BioFormatsLink#1]
Hi,

I'm use BioFormatsLink to import .czi images (containing a single image with two channels), and it works fine for images that are 4915x4915 pixels in dimension. However, when I try and import an image that is 6861x6861, I get $Failed.

Going into the BioFormatsLink code and removing the Quiet's that are littered everywhere tells me that Java is running out of memory. It would be helpful if at least this error was not silenced.

If I make a copy of the BioFormatsLink.wl file and increase the Java heap size via ReinstallJava[JVMArguments -> "-Xmx1g"] it works fine (which is my current workaround), but if I try and do the same when calling Needs["BioFormatsLink`"] either before or after, the importing now fails for all my czi images.

**Comment by SPPearce** [comment]
The following code works for me:

Needs["JLink`"];
SetOptions[InstallJava, JVMArguments -> "-Xmx1g"];
UninstallJava[];
Get["BioFormatsLink`"]

Note that if you use Needs instead of Get the second time it won't work if you rerun the code. Strangely (to me), the following code does not help:

Needs["JLink`"];
SetOptions[ReinstallJava, JVMArguments -> "-Xmx1g"];
ReinstallJava[];
Needs["BioFormatsLink`"]

**Comment by SPPearce** [comment]
Has this been fixed, or just closed?

**Comment by piotrwendykier** [comment]
It is closed, because it is not a bug - it is a feature of JLink.

**Comment by piotrwendykier** [comment]
In version 1.2.2 JVM is initialized with 3/4 of available memory. This should fix the problem with larger files.
